/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.50
 * Generated at: 2020-02-18 13:04:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ResourceBundle;
import java.util.Locale;
import model_user.CustomerDAO;
import model_user.LoginDAO;
import model_user.Login;
import model_user.Customer;
import model_shoppingcart.ItemCart;
import model_shoppingcart.ShoppingCart;
import modelMenu.MenuDAO;
import modelMenu.Menu;
import modelCuHang.DanhSachCuaHangDAO;
import modelCuHang.CuaHang;
import java.util.ArrayList;

public final class menu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("model_shoppingcart.ItemCart");
    _jspx_imports_classes.add("modelMenu.Menu");
    _jspx_imports_classes.add("model_shoppingcart.ShoppingCart");
    _jspx_imports_classes.add("modelCuHang.DanhSachCuaHangDAO");
    _jspx_imports_classes.add("model_user.Login");
    _jspx_imports_classes.add("modelMenu.MenuDAO");
    _jspx_imports_classes.add("java.util.ArrayList");
    _jspx_imports_classes.add("model_user.LoginDAO");
    _jspx_imports_classes.add("model_user.Customer");
    _jspx_imports_classes.add("java.util.ResourceBundle");
    _jspx_imports_classes.add("model_user.CustomerDAO");
    _jspx_imports_classes.add("java.util.Locale");
    _jspx_imports_classes.add("modelCuHang.CuaHang");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<title>menu động</title>\r\n");
      out.write("<style>\r\n");
      out.write(".cart span {\r\n");
      out.write("\tbackground: #f8390d;\r\n");
      out.write("\tborder-radius: 100px;\r\n");
      out.write("\tcolor: #fff;\r\n");
      out.write("\tfont-size: 1em;\r\n");
      out.write("\twidth: 30px;\r\n");
      out.write("\theight: 30px;\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\ttop: 35px;\r\n");
      out.write("\tright: 60px;\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tborder: 1px solid #E73737;\r\n");
      out.write("\tpadding: 2px 0 0;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");

		//binh thuong thi lay ngon ngu la VN
		Locale.setDefault(new Locale("vn", "VN"));
		ResourceBundle resourcebundle = ResourceBundle.getBundle("bundle/demoResource_vn_VN");

		if (session.getAttribute("language") == null) {
			resourcebundle = ResourceBundle.getBundle("bundle/demoResource_vn_VN");
		} else {
			String language = (String) session.getAttribute("language");
			if (language.equals("VN")) {
				resourcebundle = ResourceBundle.getBundle("bundle/demoResource_vn_VN");
			}
			if (language.equals("EN")) {
				resourcebundle = ResourceBundle.getBundle("bundle/demoResource_en_US");
			}
		}
	
      out.write('\r');
      out.write('\n');
      out.write('	');

		Login user = (Login) session.getAttribute("user");
	
      out.write("\r\n");
      out.write("\t<!-- top-header -->\r\n");
      out.write("\t<div class=\"header-most-top\">\r\n");
      out.write("\t\t<p>");
      out.print(resourcebundle.getString("titleIndex") );
      out.write("</p>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- //top-header -->\r\n");
      out.write("\t<!-- header-bot-->\r\n");
      out.write("\t<div class=\"header-bot\">\r\n");
      out.write("\t\t<div class=\"header-bot_inner_wthreeinfo_header_mid\">\r\n");
      out.write("\t\t\t<!-- header-bot-->\r\n");
      out.write("\t\t\t<div class=\"col-md-4 logo_agile\">\r\n");
      out.write("\t\t\t\t<h1>\r\n");
      out.write("\t\t\t\t\t<a href=\"index.html\"> <span>L</span>ighting <span>S</span>hopping\r\n");
      out.write("\t\t\t\t\t\t<img src=\"images/logo2.png\" alt=\" \">\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</h1>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- header-bot -->\r\n");
      out.write("\t\t\t<div class=\"col-md-8 header\">\r\n");
      out.write("\t\t\t\t<!-- header lists -->\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li><form method=\"post\"\r\n");
      out.write("\t\t\t\t\t\t\taction=\"ControllerShopping?action=languageVN\"\r\n");
      out.write("\t\t\t\t\t\t\tonsubmit=\"return submitForm2(this);\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"submit\" name=\"submit\" value=\"Việt Nam\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"button\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"background: none; border: none; font-size: 15px\" />\r\n");
      out.write("\t\t\t\t\t\t</form></li>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<form method=\"post\" action=\"ControllerShopping?action=languageEN\"\r\n");
      out.write("\t\t\t\t\t\t\tonsubmit=\"return submitForm2(this);\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"submit\" name=\"submit\" value=\"English\" class=\"button\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"background: none; border: none; font-size: 15px\" />\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t");

						if (user == null) {
					
      out.write("\r\n");
      out.write("\t\t\t\t\t<li><a href=\"ControllerShopping?action=checkUser\"> <span\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"fa fa-unlock-alt\" aria-hidden=\"true\"></span> ");
      out.print(resourcebundle.getString("login"));
      out.write("\r\n");
      out.write("\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"register.jsp\"> <span\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"fa fa-pencil-square-o\" aria-hidden=\"true\"></span> ");
      out.print(resourcebundle.getString("signin"));
      out.write("\r\n");
      out.write("\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t");

						} else {
					
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t");

						if (new LoginDAO().findAdminByIDLogin(user.getIdUser()) == true) {
					
      out.write("\r\n");
      out.write("\t\t\t\t\t<li><a href=\"ControllerAdmin?action=hasAdmin\">");
      out.print(resourcebundle.getString("admin") );
      out.write("</a></li>\r\n");
      out.write("\t\t\t\t\t");

						} else {
					
      out.write("\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">0357352255</a></li>\r\n");
      out.write("\t\t\t\t\t");

						}
					
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<li><a href=\"userinfo.jsp\"><span class=\"fa fa-user\"\r\n");
      out.write("\t\t\t\t\t\t\taria-hidden=\"true\"></span>");
      out.print(new CustomerDAO().mappingUserName(user.getIdUser()));
      out.write("</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"ControllerShopping?action=logout\"> <span\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"fa fa-sign-out\" aria-hidden=\"true\"></span>");
      out.print(resourcebundle.getString("logout") );
      out.write("\r\n");
      out.write("\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t");

						}
					
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<!-- //header lists -->\r\n");
      out.write("\t\t\t\t<!-- search -->\r\n");
      out.write("\t\t\t\t<div class=\"agileits_search\">\r\n");
      out.write("\t\t\t\t\t<form action=\"ControllerShopping?action=search\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t<input name=\"Search\" type=\"search\"\r\n");
      out.write("\t\t\t\t\t\t\tplaceholder=\"");
      out.print(resourcebundle.getString("inputSearch") );
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\tvalue=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${searchTitle }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" required=\"\">\r\n");
      out.write("\t\t\t\t\t\t<button type=\"submit\" class=\"btn btn-default\"\r\n");
      out.write("\t\t\t\t\t\t\taria-label=\"Left Align\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"fa fa-search\" aria-hidden=\"true\"> </span>\r\n");
      out.write("\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- //search -->\r\n");
      out.write("\t\t\t\t<!-- cart details -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"top_nav_right\">\r\n");
      out.write("\t\t\t\t\t<div class=\"wthreecartaits wthreecartaits2 cart cart box_1\">\r\n");
      out.write("\t\t\t\t\t\t<form action=\"#\" method=\"post\" class=\"last\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" name=\"cmd\" value=\"_cart\"> <input\r\n");
      out.write("\t\t\t\t\t\t\t\ttype=\"hidden\" name=\"display\" value=\"1\"> <a\r\n");
      out.write("\t\t\t\t\t\t\t\thref=\"GioHang.jsp\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<button class=\"w3view-cart\" type=\"submit\" name=\"submit\" value=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"fa fa-cart-arrow-down\" aria-hidden=\"true\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"cart\">\r\n");
      out.write("\t\t\t\t\t\t\t\t");

									if (session.getAttribute("numbercart") == null) {
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"GioHang.jsp\" class=\"cart-in\"> <span id=\"resultcart\">0</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t");

									} else {
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"GioHang.jsp\" class=\"cart-in\"> <span id=\"resultcart\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.numbercart }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t");

									}
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- //cart details -->\r\n");
      out.write("\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- shop locator (popup) -->\r\n");
      out.write("\t<!-- Button trigger modal(shop-locator) -->\r\n");
      out.write("\t<div id=\"small-dialog1\" class=\"mfp-hide\">\r\n");
      out.write("\t\t<div class=\"select-city\">\r\n");
      out.write("\t\t\t<h3>Please Select Your Location</h3>\r\n");
      out.write("\t\t\t<select class=\"list_of_cities\">\r\n");
      out.write("\t\t\t\t<optgroup label=\"Thành Phố Hồ Chí Minh\">\r\n");
      out.write("\t\t\t\t\t<option selected style=\"display: none; color: #eee;\">Select\r\n");
      out.write("\t\t\t\t\t\tCity</option>\r\n");
      out.write("\t\t\t\t\t");

						for (CuaHang c : DanhSachCuaHangDAO.getListCH("TP.HCM")) {
					
      out.write("\r\n");
      out.write("\t\t\t\t\t<option>");
      out.print(c.getName());
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t");

						}
					
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</optgroup>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<optgroup label=\"Long An\">\r\n");
      out.write("\t\t\t\t\t");

						for (CuaHang c : DanhSachCuaHangDAO.getListCH("Long An")) {
					
      out.write("\r\n");
      out.write("\t\t\t\t\t<option>");
      out.print(c.getName());
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t");

						}
					
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</optgroup>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</select>\r\n");
      out.write("\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- //shop locator (popup) -->\r\n");
      out.write("\t<!-- signin Model -->\r\n");
      out.write("\t<!-- Modal1 -->\r\n");
      out.write("\t<div class=\"modal fade\" id=\"myModal1\" tabindex=\"-1\" role=\"dialog\">\r\n");
      out.write("\t\t<div class=\"modal-dialog\">\r\n");
      out.write("\t\t\t<!-- Modal content-->\r\n");
      out.write("\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"modal-body modal-body-sub_agile\">\r\n");
      out.write("\t\t\t\t\t<div class=\"main-mailposi\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"fa fa-envelope-o\" aria-hidden=\"true\"></span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"modal_body_left modal_body_left1\">\r\n");
      out.write("\t\t\t\t\t\t<h3 class=\"agileinfo_sign\">Sign In</h3>\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\tSign In now, Let's start your Grocery Shopping. Don't have an\r\n");
      out.write("\t\t\t\t\t\t\taccount? <a href=\"#\" data-toggle=\"modal\" data-target=\"#myModal2\">\r\n");
      out.write("\t\t\t\t\t\t\t\tSign Up Now</a>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t<form action=\"#\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"styled-input agile-styled-input-top\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" placeholder=\"User Name\" name=\"Name\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\trequired=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"styled-input\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"password\" placeholder=\"Password\" name=\"password\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\trequired=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"submit\" value=\"Sign In\">\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- //Modal content-->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- //Modal1 -->\r\n");
      out.write("\t<!-- //signin Model -->\r\n");
      out.write("\t<!-- signup Model -->\r\n");
      out.write("\t<!-- Modal2 -->\r\n");
      out.write("\t<div class=\"modal fade\" id=\"myModal2\" tabindex=\"-1\" role=\"dialog\">\r\n");
      out.write("\t\t<div class=\"modal-dialog\">\r\n");
      out.write("\t\t\t<!-- Modal content-->\r\n");
      out.write("\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"modal-body modal-body-sub_agile\">\r\n");
      out.write("\t\t\t\t\t<div class=\"main-mailposi\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"fa fa-envelope-o\" aria-hidden=\"true\"></span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"modal_body_left modal_body_left1\">\r\n");
      out.write("\t\t\t\t\t\t<h3 class=\"agileinfo_sign\">Sign Up</h3>\r\n");
      out.write("\t\t\t\t\t\t<p>Come join the Grocery Shoppy! Let's set up your Account.</p>\r\n");
      out.write("\t\t\t\t\t\t<form action=\"#\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"styled-input agile-styled-input-top\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" placeholder=\"Name\" name=\"Name\" required=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"styled-input\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"email\" placeholder=\"E-mail\" name=\"Email\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\trequired=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"styled-input\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"password\" placeholder=\"Password\" name=\"password\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tid=\"password1\" required=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"styled-input\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"password\" placeholder=\"Confirm Password\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"Confirm Password\" id=\"password2\" required=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"submit\" value=\"Sign Up\">\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\">By clicking register, I agree to your terms</a>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- //Modal content-->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- //Modal2 -->\r\n");
      out.write("\t<!-- //signup Model -->\r\n");
      out.write("\t<!-- //header-bot -->\r\n");
      out.write("\t<!-- navigation -->\r\n");
      out.write("\r\n");
      out.write("\t");

		ArrayList<Menu> lisMenu = MenuDAO.getListMenu();
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"ban-top\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"agileits-navi_search\" style=\"margin-left: -100px;\">\r\n");
      out.write("\t\t\t\t<form action=\"ControllerShopping?action=menu\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t<select id=\"agileinfo-nav_search\" onchange=\"this.form.submit()\"\r\n");
      out.write("\t\t\t\t\t\tname=\"value\">\r\n");
      out.write("\t\t\t\t\t\t<!-- dua den servlet cho nay de loc san pham theo nhom -->\r\n");
      out.write("\t\t\t\t\t\t");

							ArrayList<String> listMenuSub = new MenuDAO().getListSub();
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<option value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${groupProduct }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write('"');
      out.write('>');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${groupProduct}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t");

							for (String m : listMenuSub) {
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<option value=\"");
      out.print(m);
      out.write('"');
      out.write('>');
      out.print(m);
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t");

							}
						
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"top_nav_left\">\r\n");
      out.write("\t\t\t\t<nav class=\"navbar navbar-default\">\r\n");
      out.write("\t\t\t\t\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t\t\t\t\t<!-- Brand and toggle get grouped for better mobile display -->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"navbar-header\">\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"button\" class=\"navbar-toggle collapsed\"\r\n");
      out.write("\t\t\t\t\t\t\t\tdata-toggle=\"collapse\"\r\n");
      out.write("\t\t\t\t\t\t\t\tdata-target=\"#bs-example-navbar-collapse-1\"\r\n");
      out.write("\t\t\t\t\t\t\t\taria-expanded=\"false\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"sr-only\">Toggle navigation</span> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"icon-bar\"></span> <span class=\"icon-bar\"></span> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<!-- Collect the nav links, forms, and other content for toggling -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<!-- chay for de lay menu -->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"collapse navbar-collapse menu--shylock\"\r\n");
      out.write("\t\t\t\t\t\t\tid=\"bs-example-navbar-collapse-1\">\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"nav navbar-nav menu__list\" style=\"margin-top: -5%;\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t");

									for (Menu m : lisMenu) {
										if (m.isDropdown() == false) {
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"\"><a class=\"nav-stylehead\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"");
      out.print(m.getLink());
      out.write('"');
      out.write('>');
      out.print(m.getName());
      out.write("</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t");

									} else if (m.isDropdown() == true) {
								
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"dropdown\"><a href=\"");
      out.print(m.getLink());
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"dropdown-toggle nav-stylehead\" data-toggle=\"dropdown\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\trole=\"button\" aria-haspopup=\"true\" aria-expanded=\"false\">");
      out.print(m.getName());
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"caret\"></span> </a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul class=\"dropdown-menu agile_short_dropdown\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");

											for (Menu sub : m.getListSubMenu()) {
										
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"");
      out.print(sub.getLink());
      out.write('"');
      out.write('>');
      out.print(sub.getName());
      out.write("</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");

											}
										
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t");

									}
									}
								
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</nav>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t\"use strict\";\r\n");
      out.write("\t\tfunction submitForm2(oFormElement) {\r\n");
      out.write("\t\t\tvar xhr = new XMLHttpRequest();\r\n");
      out.write("\t\t\txhr.onload = function() {\r\n");
      out.write("\t\t\t\tswal({\r\n");
      out.write("\t\t\t\t\tposition : 'top-end',\r\n");
      out.write("\t\t\t\t\ttype : 'success',\r\n");
      out.write("\t\t\t\t\ttitle : xhr.responseText,\r\n");
      out.write("\t\t\t\t\tshowConfirmButton : false,\r\n");
      out.write("\t\t\t\t\ttimer : 1000\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\twindow.setTimeout(function() {\r\n");
      out.write("\t\t\t\t\tlocation.reload();\r\n");
      out.write("\t\t\t\t}, 1000);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\txhr.open(oFormElement.method, oFormElement.action, true);\r\n");
      out.write("\t\t\txhr.send(new FormData(oFormElement));\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
