/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.50
 * Generated at: 2020-03-16 04:24:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import model_user.CustomerDAO;
import model_user.Customer;
import java.text.DecimalFormat;
import model_user.Login;
import model_shoppingcart.InvoiceDB;
import model_shoppingcart.Invoice;
import java.util.ArrayList;

public final class userinfo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("model_shoppingcart.Invoice");
    _jspx_imports_classes.add("model_user.Customer");
    _jspx_imports_classes.add("model_shoppingcart.InvoiceDB");
    _jspx_imports_classes.add("model_user.CustomerDAO");
    _jspx_imports_classes.add("java.text.DecimalFormat");
    _jspx_imports_classes.add("model_user.Login");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"zxx\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<title>User info</title>\r\n");
      out.write("<!--/tags -->\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<meta name=\"keywords\"\r\n");
      out.write("\tcontent=\"Grocery Shoppy Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, \r\n");
      out.write("Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design\" />\r\n");
      out.write("<script>\r\n");
      out.write("\taddEventListener(\"load\", function() {\r\n");
      out.write("\t\tsetTimeout(hideURLbar, 0);\r\n");
      out.write("\t}, false);\r\n");
      out.write("\r\n");
      out.write("\tfunction hideURLbar() {\r\n");
      out.write("\t\twindow.scrollTo(0, 1);\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("<!--//tags -->\r\n");
      out.write("<link href=\"css/bootstrap.css\" rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\tmedia=\"all\" />\r\n");
      out.write("<link href=\"css/style.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\" />\r\n");
      out.write("<link href=\"css/font-awesome.css\" rel=\"stylesheet\">\r\n");
      out.write("<!--pop-up-box-->\r\n");
      out.write("<link href=\"css/popuo-box.css\" rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\tmedia=\"all\" />\r\n");
      out.write("<!--//pop-up-box-->\r\n");
      out.write("<!-- price range -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/jquery-ui1.css\">\r\n");
      out.write("<!-- fonts -->\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"//fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- phan trang -->\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.3.1.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap.min.css\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("\t<script\r\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/6.11.4/sweetalert2.all.js\"></script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("/* Full-width input fields */\r\n");
      out.write("input[type=text], input[type=password] {\r\n");
      out.write("\twidth: 80%;\r\n");
      out.write("\tpadding: 5px 5px;\r\n");
      out.write("\tmargin: 8px 0;\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\tborder: 1px solid #ccc;\r\n");
      out.write("\tbox-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Set a style for all buttons */\r\n");
      out.write("\r\n");
      out.write("/* Extra styles for the cancel button */\r\n");
      out.write(".cancelbtn {\r\n");
      out.write("\twidth: auto;\r\n");
      out.write("\tpadding: 10px 18px;\r\n");
      out.write("\tbackground-color: #f44336;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Center the image and position the close button */\r\n");
      out.write("span.psw {\r\n");
      out.write("\tfloat: right;\r\n");
      out.write("\tpadding-top: 16px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* The Modal (background) */\r\n");
      out.write(".modal {\r\n");
      out.write("\tdisplay: none; /* Hidden by default */\r\n");
      out.write("\tposition: fixed; /* Stay in place */\r\n");
      out.write("\tz-index: 1; /* Sit on top */\r\n");
      out.write("\tleft: 0;\r\n");
      out.write("\ttop: 0;\r\n");
      out.write("\twidth: 100%; /* Full width */\r\n");
      out.write("\theight: 100%; /* Full height */\r\n");
      out.write("\toverflow: auto; /* Enable scroll if needed */\r\n");
      out.write("\tbackground-color: rgb(0, 0, 0); /* Fallback color */\r\n");
      out.write("\tbackground-color: rgba(0, 0, 0, 0.4); /* Black w/ opacity */\r\n");
      out.write("\tpadding-top: 60px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Modal Content/Box */\r\n");
      out.write(".modal-content {\r\n");
      out.write("\tbackground-color: #fefefe;\r\n");
      out.write("\tmargin: 5% auto 15% auto;\r\n");
      out.write("\t/* 5% from the top, 15% from the bottom and centered */\r\n");
      out.write("\tborder: 1px solid #888;\r\n");
      out.write("\twidth: 50%; /* Could be more or less, depending on screen size */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* The Close Button (x) */\r\n");
      out.write(".close {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tright: 25px;\r\n");
      out.write("\ttop: 0;\r\n");
      out.write("\tcolor: #000;\r\n");
      out.write("\tfont-size: 35px;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".close:hover, .close:focus {\r\n");
      out.write("\tcolor: red;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Add Zoom Animation */\r\n");
      out.write(".animate {\r\n");
      out.write("\t-webkit-animation: animatezoom 0.6s;\r\n");
      out.write("\tanimation: animatezoom 0.6s\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@\r\n");
      out.write("-webkit-keyframes animatezoom {\r\n");
      out.write("\tfrom {-webkit-transform: scale(0)\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("to {\r\n");
      out.write("\t-webkit-transform: scale(1)\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("@\r\n");
      out.write("keyframes animatezoom {\r\n");
      out.write("\tfrom {transform: scale(0)\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("to {\r\n");
      out.write("\ttransform: scale(1)\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Change styles for span and cancel button on extra small screens */\r\n");
      out.write("@media screen and (max-width: 300px) {\r\n");
      out.write("\tspan.psw {\r\n");
      out.write("\t\tdisplay: block;\r\n");
      out.write("\t\tfloat: none;\r\n");
      out.write("\t}\r\n");
      out.write("\t.cancelbtn {\r\n");
      out.write("\t\twidth: 100%;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t");

		if (session.getAttribute("user") == null) {
	
      out.write("\r\n");
      out.write("\t<!-- top-header -->\r\n");
      out.write("\t");
      if (true) {
        _jspx_page_context.forward("login.jsp");
        return;
      }
      out.write('\r');
      out.write('\n');
      out.write('	');

		}
	
      out.write('\r');
      out.write('\n');
      out.write('	');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "menu.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- payment page-->\r\n");
      out.write("\t<div class=\"privacy\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<!-- tittle heading -->\r\n");
      out.write("\t\t\t<h3 class=\"tittle-w3l\" style=\"font-size: 24px\">\r\n");
      out.write("\t\t\t\tTHÔNG TIN KHÁCH HÀNG <span class=\"heading-style\"> <i></i> <i></i>\r\n");
      out.write("\t\t\t\t\t<i></i>\r\n");
      out.write("\t\t\t\t</span>\r\n");
      out.write("\t\t\t</h3>\r\n");
      out.write("\t\t\t<!-- //tittle heading -->\r\n");
      out.write("\t\t\t<div class=\"checkout-right\">\r\n");
      out.write("\t\t\t\t<!--Horizontal Tab-->\r\n");
      out.write("\t\t\t\t<div id=\"parentHorizontalTab\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"resp-tabs-list hor_1\">\r\n");
      out.write("\t\t\t\t\t\t<li style=\"font-size: 16px;\">Đơn hàng hiện tại</li>\r\n");
      out.write("\t\t\t\t\t\t<li style=\"font-size: 16px;\">Thông tin khách hàng</li>\r\n");
      out.write("\t\t\t\t\t\t<li style=\"font-size: 16px;\">Đơn hàng đã đặt</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t<div class=\"resp-tabs-container hor_1\">\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"vertical_post check_box_agile\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h5>COD</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"checkbox\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"check_box_one cashon_delivery\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label class=\"anim\"> <input type=\"checkbox\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"checkbox\"> <span> We also accept\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tCredit/Debit card on delivery. Please Check with the agent.</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- thong tin ca nhan cua khach hang -->\r\n");
      out.write("\t\t\t\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- thong tin -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

										Login user = (Login) session.getAttribute("user");
										Customer c = new CustomerDAO().mappingUserInfo(user.getIdUser());
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td><b>Tên đăng nhập: &nbsp; &nbsp; &nbsp; &nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t&nbsp; &nbsp; &nbsp;</b></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td>");
      out.print(c.getUsername());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td><b>Tên thực: </b></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td>");
      out.print(c.getFullName());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td><b>Email: </b></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td>");
      out.print(user.getEmail());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td><b>Số điện thoại: </b></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td>");
      out.print(c.getPhone());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td><b>Địa chỉ: </b></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td>");
      out.print(c.getAddress());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- button cap nhat -->\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><button class=\"btn btn-success\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tonclick=\"document.getElementById('id01').style.display='block'\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tstyle=\"width: auto;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span>Thay đổi</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</button></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"vertical_post\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- hien thi danh sach don hang cua khach hang -->\r\n");
      out.write("\t\t\t\t\t\t\t\t");

									ArrayList<Invoice> list = new InvoiceDB().getListInvoiceOfAUser(user.getIdUser());
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- ke table hien thi -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<table id=\"example\" class=\"table table-hover\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"width: 100%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td colspan=\"6\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${numberSearch }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th title=\"Số thứ tự\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"width: 10%; color: black; font-size: 16px;\">STT</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th style=\"width: 10%; color: black; font-size: 16px;\">Mã\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\thóa đơn</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th style=\"width: 20%; color: black; font-size: 16px;\">Ngày\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tđặt hàng</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th style=\"width: 10%; color: black; font-size: 16px;\">Tổng\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tgiá</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th style=\"width: 10%; color: black; font-size: 16px;\">Trạng\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tthái</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th style=\"width: 15%; color: black; font-size: 16px;\"></th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");

											int count = 1;
											for (Invoice i : list) {
										
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td style=\"color: black; font-size: 16px;\">");
      out.print(count);
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td style=\"color: black; font-size: 16px;\">");
      out.print(i.getNumberInvoice());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");

												DecimalFormat formatter = new DecimalFormat("###,###,###");
											
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");

												java.text.DateFormat df = new java.text.SimpleDateFormat("dd/MM/yyyy");
											
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td style=\"color: black; font-size: 16px;\">");
      out.print(df.format(i.getToday().getTime()));
      out.write("</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td style=\"color: black; font-size: 16px;\">");
      out.print(formatter.format(i.getShop().totalPrice()));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");
if(i.isProcess() == false){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td style=\"color: red; font-size: 16px;\">Chưa xử lí</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");
}else{ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td style=\"color: green; font-size: 16px;\">Đã xử lí</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td style=\"color: black; font-size: 16px; text-align: center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<a\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\thref=\"ControllerShopping?action=detailInvoice&id=");
      out.print(i.getNumberInvoice());
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"font-size: 24px;\"> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"fa fa-info-circle\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");

											count++;
											}
										
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!--Plug-in Initialisation-->\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!-- //payment page -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"id01\" class=\"modal\">\r\n");
      out.write("\t\t<form class=\"modal-content animate\"\r\n");
      out.write("\t\t\tonsubmit=\"return submitForm2(this);\"\r\n");
      out.write("\t\t\taction=\"ControllerShopping?action=userInfoUpdate\" method=\"post\">\r\n");
      out.write("\t\t\t<div class=\"imgcontainer\">\r\n");
      out.write("\t\t\t\t<span onclick=\"document.getElementById('id01').style.display='none'\"\r\n");
      out.write("\t\t\t\t\tclass=\"close\" title=\"Close Modal\">&times;</span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<table style=\"width: 100%;\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td><label><b>Tên đăng nhập</b></label></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"userName\"\r\n");
      out.write("\t\t\t\t\t\t\tvalue=\"");
      out.print(c.getUsername());
      out.write("\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td><label><b>Tên thực</b></label></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"realName\"\r\n");
      out.write("\t\t\t\t\t\t\tvalue=\"");
      out.print(c.getFullName());
      out.write("\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td><label><b>Email</b></label></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"email\"\r\n");
      out.write("\t\t\t\t\t\t\tvalue=\"");
      out.print(user.getEmail());
      out.write("\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td><label><b>Số điện thoại</b></label></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"phone\" value=\"");
      out.print(c.getPhone());
      out.write("\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td><label><b>Địa chỉ</b></label></td>\r\n");
      out.write("\t\t\t\t\t\t<td><textarea rows=\"3\" cols=\"50\" name=\"address\">");
      out.print(c.getAddress());
      out.write("</textarea>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div style=\"background-color: #f1f1f1; text-align: center\">\r\n");
      out.write("\t\t\t\t<button type=\"submit\" class=\"btn btn-success\">Cập nhật</button>\r\n");
      out.write("\t\t\t\t<button class=\"btn btn-danger\"\r\n");
      out.write("\t\t\t\t\tonclick=\"document.getElementById('id01').style.display='none'\"\r\n");
      out.write("\t\t\t\t\tclass=\"cancelbtn\">Cancel</button>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- goi servlet -->\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\r\n");
      out.write("\t\tfunction submitForm2(oFormElement) {\r\n");
      out.write("\t\t\t\"use strict\";\r\n");
      out.write("\t\t\tvar xhr = new XMLHttpRequest();\r\n");
      out.write("\t\t\txhr.onload = function() {\r\n");
      out.write("\t\t\t\tswal({\r\n");
      out.write("\t\t\t\t\tposition : 'top-end',\r\n");
      out.write("\t\t\t\t\ttype : 'success',\r\n");
      out.write("\t\t\t\t\ttitle : xhr.responseText,\r\n");
      out.write("\t\t\t\t\tshowConfirmButton : false,\r\n");
      out.write("\t\t\t\t\ttimer : 1000\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\twindow.setTimeout(function() {\r\n");
      out.write("\t\t\t\t\tlocation.reload();\r\n");
      out.write("\t\t\t\t}, 1000);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t//.text(....)\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\txhr.open(oFormElement.method, oFormElement.action, true);\r\n");
      out.write("\t\t\txhr.send(new FormData(oFormElement));\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t// Get the modal\r\n");
      out.write("\t\tvar modal = document.getElementById('id01');\r\n");
      out.write("\r\n");
      out.write("\t\t// When the user clicks anywhere outside of the modal, close it\r\n");
      out.write("\t\twindow.onclick = function(event) {\r\n");
      out.write("\t\t\tif (event.target == modal) {\r\n");
      out.write("\t\t\t\tmodal.style.display = \"none\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tvar coll = document.getElementsByClassName(\"collapsible1\");\r\n");
      out.write("\t\tvar i;\r\n");
      out.write("\r\n");
      out.write("\t\tfor (i = 0; i < coll.length; i++) {\r\n");
      out.write("\t\t\tcoll[i].addEventListener(\"click\", function() {\r\n");
      out.write("\t\t\t\tthis.classList.toggle(\"active\");\r\n");
      out.write("\t\t\t\tvar content = this.nextElementSibling;\r\n");
      out.write("\t\t\t\tif (content.style.display === \"block\") {\r\n");
      out.write("\t\t\t\t\tcontent.style.display = \"none\";\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\tcontent.style.display = \"block\";\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- easy-responsive-tabs -->\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\t\thref=\"css/easy-responsive-tabs.css \">\r\n");
      out.write("\t<script src=\"js/easyResponsiveTabs.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t$(document).ready(function() {\r\n");
      out.write("\t\t\t//Horizontal Tab\r\n");
      out.write("\t\t\t$('#parentHorizontalTab').easyResponsiveTabs({\r\n");
      out.write("\t\t\t\ttype : 'default', //Types: default, vertical, accordion\r\n");
      out.write("\t\t\t\twidth : 'auto', //auto or any width like 600px\r\n");
      out.write("\t\t\t\tfit : true, // 100% fit in a container\r\n");
      out.write("\t\t\t\ttabidentify : 'hor_1', // The tab groups identifier\r\n");
      out.write("\t\t\t\tactivate : function(event) { // Callback function if tab is switched\r\n");
      out.write("\t\t\t\t\tvar $tab = $(this);\r\n");
      out.write("\t\t\t\t\tvar $info = $('#nested-tabInfo');\r\n");
      out.write("\t\t\t\t\tvar $name = $('span', $info);\r\n");
      out.write("\t\t\t\t\t$name.text($tab.text());\r\n");
      out.write("\t\t\t\t\t$info.show();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<!-- //easy-responsive-tabs -->\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t$(document).ready(function() {\r\n");
      out.write("\t\t\t$('#example').dataTable();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<!-- smoothscroll -->\r\n");
      out.write("\t<script src=\"js/SmoothScroll.min.js\"></script>\r\n");
      out.write("\t<!-- //smoothscroll -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- start-smooth-scrolling -->\r\n");
      out.write("\t<script src=\"js/move-top.js\"></script>\r\n");
      out.write("\t<script src=\"js/easing.js\"></script>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tjQuery(document).ready(function($) {\r\n");
      out.write("\t\t\t$(\".scroll\").click(function(event) {\r\n");
      out.write("\t\t\t\tevent.preventDefault();\r\n");
      out.write("\t\t\t\t$('html,body').animate({\r\n");
      out.write("\t\t\t\t\tscrollTop : $(this.hash).offset().top\r\n");
      out.write("\t\t\t\t}, 1000);\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<!-- //end-smooth-scrolling -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- smooth-scrolling-of-move-up -->\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t$(document).ready(function() {\r\n");
      out.write("\t\t\t/*\r\n");
      out.write("\t\t\tvar defaults = {\r\n");
      out.write("\t\t\t\tcontainerID: 'toTop', // fading element id\r\n");
      out.write("\t\t\t\tcontainerHoverID: 'toTopHover', // fading element hover id\r\n");
      out.write("\t\t\t\tscrollSpeed: 1200,\r\n");
      out.write("\t\t\t\teasingType: 'linear' \r\n");
      out.write("\t\t\t};\r\n");
      out.write("\t\t\t */\r\n");
      out.write("\t\t\t$().UItoTop({\r\n");
      out.write("\t\t\t\teasingType : 'easeOutQuart'\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<!-- //smooth-scrolling-of-move-up -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- for bootstrap working -->\r\n");
      out.write("\t<script src=\"js/bootstrap.js\"></script>\r\n");
      out.write("\t<!-- //for bootstrap working -->\r\n");
      out.write("\t<!-- //js-files -->\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
