/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.50
 * Generated at: 2020-02-18 13:05:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin.product;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.text.DecimalFormat;
import java.util.List;
import model_product.ProductDAO;
import model_product.Product;
import java.util.ArrayList;

public final class quanlisanpham_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("model_product.ProductDAO");
    _jspx_imports_classes.add("java.text.DecimalFormat");
    _jspx_imports_classes.add("model_product.Product");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Quản lí sản phẩm</title>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tfunction checkInput() {\r\n");
      out.write("\t\tif (isNaN(checkValidation.price.value)) {\r\n");
      out.write("\t\t\talert(\"Giá bán phải là số\");\r\n");
      out.write("\t\t\tcheckValidation.price.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif (isNaN(checkValidation.discount.value)) {\r\n");
      out.write("\t\t\talert(\"Giảm giá phải là số\");\r\n");
      out.write("\t\t\tcheckValidation.discount.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif (isNaN(checkValidation.soLuong.value)) {\r\n");
      out.write("\t\t\talert(\"Số lượng phải là số\");\r\n");
      out.write("\t\t\tcheckValidation.soLuong.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\treturn true;\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<meta name=\"keywords\"\r\n");
      out.write("\tcontent=\"Glance Design Dashboard Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, \r\n");
      out.write("SmartPhone Compatible web template, free WebDesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design\" />\r\n");
      out.write("<script type=\"application/x-javascript\">\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t addEventListener(\"load\", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap Core CSS -->\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/newcss/bootstrap.css\"\r\n");
      out.write("\trel='stylesheet' type='text/css' />\r\n");
      out.write("\r\n");
      out.write("<!-- Custom CSS -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/newcss/style.css\" />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- font-awesome icons CSS -->\r\n");
      out.write("<link href=\"");
      out.print(request.getContextPath());
      out.write("/newcss/font-awesome.css\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<!-- //font-awesome icons CSS-->\r\n");
      out.write("\r\n");
      out.write("<!-- side nav css file -->\r\n");
      out.write("<link href=\"");
      out.print(request.getContextPath());
      out.write("/newcss/SidebarNav.min.css\"\r\n");
      out.write("\tmedia='all' rel='stylesheet' type='text/css' />\r\n");
      out.write("<!-- //side nav css file -->\r\n");
      out.write("\r\n");
      out.write("<!-- js-->\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/newjs/jquery-1.11.1.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/newjs/modernizr.custom.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!--webfonts-->\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"//fonts.googleapis.com/css?family=PT+Sans:400,400i,700,700i&amp;subset=cyrillic,cyrillic-ext,latin-ext\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<!--//webfonts-->\r\n");
      out.write("\r\n");
      out.write("<!-- Metis Menu -->\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/newjs/metisMenu.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/newjs/custom.js\"></script>\r\n");
      out.write("<link href=\"");
      out.print(request.getContextPath());
      out.write("/newjs/custom.css\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<!-- -->\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.3.1.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap.min.js\"></script>\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap.min.css\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<!--//Metis Menu -->\r\n");
      out.write("<style>\r\n");
      out.write("#chartdiv {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 295px;\r\n");
      out.write("}\r\n");
      out.write("/* Full-width input fields */\r\n");
      out.write("input[type=text],input[type=number] {\r\n");
      out.write("\twidth: 90%;\r\n");
      out.write("\tpadding: 3px 3px;\r\n");
      out.write("\tmargin: 8px 0;\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\tborder: 1px solid #ccc;\r\n");
      out.write("\tbox-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<!-- requried-jsfiles-for owl -->\r\n");
      out.write("<link href=\"");
      out.print(request.getContextPath());
      out.write("/cssAdmin/owl.carousel.css\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/jsAdmin/owl.carousel.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\t\t$(\"#owl-demo\").owlCarousel({\r\n");
      out.write("\t\t\titems : 3,\r\n");
      out.write("\t\t\tlazyLoad : true,\r\n");
      out.write("\t\t\tautoPlay : true,\r\n");
      out.write("\t\t\tpagination : true,\r\n");
      out.write("\t\t\tnav : true,\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("<!-- //requried-jsfiles-for owl -->\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/6.11.4/sweetalert2.all.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"cbp-spmenu-push\">\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/admin/menu.jsp", out, false);
      out.write("\r\n");
      out.write("\t<!-- main content start-->\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<div id=\"page-wrapper\">\r\n");
      out.write("\t\t<div class=\"main-page\">\r\n");
      out.write("\t\t\t<div class=\"col_3\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<h2 style=\"text-align: center\">QUẢN LÍ SẢN PHẨM</h2>\r\n");
      out.write("\t\t\t\t<div class=\"button_set_one\"\r\n");
      out.write("\t\t\t\t\tstyle=\"width: 85%; float: right; margin-right: 8%;\">\r\n");
      out.write("\t\t\t\t\t<div style=\"float: right; margin-right: 2%;\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-default\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"\tfa fa-files-o\"></span>&nbsp;Import excel\r\n");
      out.write("\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t<a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"");
      out.print(request.getContextPath());
      out.write("/ControllerProduct?action=displayReport\"><button\r\n");
      out.write("\t\t\t\t\t\t\t\ttype=\"button\" class=\"btn btn-default\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"fa fa-file-text-o\"></span>&nbsp;Xuất excel\r\n");
      out.write("\t\t\t\t\t\t\t</button></a>\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-default\" id='btn'\r\n");
      out.write("\t\t\t\t\t\t\tonclick='printFunc();'>\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"fa fa-print\"></span>&nbsp;In\r\n");
      out.write("\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-warning\" data-toggle=\"modal\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-target=\"#myModal\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"fa fa-plus-square-o\"></span>&nbsp;Thêm mới\r\n");
      out.write("\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- the hien noi dung o day -->\r\n");
      out.write("\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\tstyle=\"width: 92%; margin-right: 2%; float: right; margin-top: -3%;\">\r\n");
      out.write("\t\t\t\t\t<div class=\"bs-example widget-shadow table-responsive\"\r\n");
      out.write("\t\t\t\t\t\tdata-example-id=\"hoverable-table\">\r\n");
      out.write("\t\t\t\t\t\t<table id=\"example\" class=\"table table-hover\" style=\"width: 100%\">\r\n");
      out.write("\t\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td colspan=\"6\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${numberSearch }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th title=\"Số thứ tự\" style=\"width: 5%\">STT</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th title=\"Mã sản phẩm\" style=\"width: 10%\">Mã</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th style=\"width: 20%\" title=\"Tên SP\">Tên</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th style=\"width: 10%\">Giá bán</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th style=\"width: 10%\">Hình ảnh</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th style=\"width: 10%\">Hoạt động</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t");

									ArrayList<Product> list = new ProductDAO().getDemo();
									ArrayList<Product> listSearch = (ArrayList<Product>) request.getAttribute("listSearchID");
									if (listSearch != null) {
										list = listSearch;
									}
									int count = 1;
									for (Product c : list) {
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>");
      out.print(count);
      out.write("</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>");
      out.print(c.getId());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>");
      out.print(c.getName());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

										DecimalFormat formatter = new DecimalFormat("###,###,###");
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>");
      out.print(formatter.format(c.getPrice()));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"");
      out.print(request.getContextPath());
      out.write('/');
      out.print(c.getLinkHA1());
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"img-responsive\" style=\"width: 30%\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<form\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\taction=\"");
      out.print(request.getContextPath());
      out.write("/ControllerProduct?action=remove&id=");
      out.print(c.getId());
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tonsubmit=\"return submitForm(this);\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<button type=\"submit\" class=\"btn btn-danger btn-sm\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"font-size: 14px;\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tonclick=\"if (!confirm('bạn có chắc chắn xóa SP: ' + ");
      out.print(c.getId());
      out.write(" +'?')) { return false }\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"fa fa-trash-o\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td>&nbsp;<a\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\thref=\"");
      out.print(request.getContextPath());
      out.write("/ControllerProduct?action=find&id=");
      out.print(c.getId());
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"btn btn-primary btn-sm\" style=\"font-size: 13px;\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"fa fa-edit\"></span></a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td>&nbsp;<a\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\thref=\"");
      out.print(request.getContextPath());
      out.write("/ControllerProduct?action=view&id=");
      out.print(c.getId());
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"btn btn-primary btn-sm\" style=\"font-size: 14px;\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"fa fa-info-circle\"></span></a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t");

									count++;
									}
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"modal fade\" id=\"myModal\" role=\"dialog\">\r\n");
      out.write("\t\t<div class=\"modal-dialog modal-lg\">\r\n");
      out.write("\t\t\t<form name=\"checkValidation\"\r\n");
      out.write("\t\t\t\taction=\"");
      out.print(request.getContextPath());
      out.write("/ControllerProduct?action=add\"\r\n");
      out.write("\t\t\t\tmethod=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("\t\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("\t\t\t\t\t\t<h4 class=\"modal-title\" style=\"text-align: center\">\r\n");
      out.write("\t\t\t\t\t\t\t<b>THÊM SẢM PHẨM</b>\r\n");
      out.write("\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t\t\t<table style=\"width: 100%;\">\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><div class=\"input-group\" style=\"display: grid;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label for=\"ma\"><b>Mã sản phẩm</b></label> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvalue=\"");
      out.print(ProductDAO.idDynamic());
      out.write("\" name=\"id\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"input-group\" style=\"display: grid;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label for=\"ten\"><b>Tên sản phẩm</b></label> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttype=\"text\" placeholder=\"Nhập tên sản phẩm\" name=\"name\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\trequired>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"input-group\" style=\"display: grid;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label for=\"ten\"><b>Mô tả</b></label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<textarea rows=\"2\" cols=\"30\" name=\"description\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><div class=\"input-group \" style=\"display: grid;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label for=\"gia\"><b>Giá bán</b></label> <input type=\"number\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"Giá bán sản phẩm\" min=\"0\" name=\"price\" required>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><div class=\"input-group \" style=\"display: grid;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label for=\"giam\"><b>Giảm giá</b></label> <input type=\"number\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"Giảm giá\" min=\"0\" name=\"discount\" required>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><div class=\"input-group \" style=\"display: grid;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label for=\"gia\"><b>Số lượng nhập</b></label> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttype=\"number\" min=\"0\" placeholder=\"Giá bán sản phẩm\" name=\"soLuong\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\trequired>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><div class=\"input-group \" style=\"display: grid;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label for=\"giam\"><b>Công suất</b></label> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"Giảm giá\" name=\"congSuat\" required>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"input-group\" style=\"display: grid;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label for=\"mota\"><b>Điện áp</b></label> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"Mô tả sản phẩm\" name=\"dienAp\" required>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><div class=\"input-group\" style=\"display: grid;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label for=\"mota\"><b>Thời gian bảo hành</b></label> <select\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tname=\"baoHanh\" style=\"width: 90%; padding: 3px 3px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");

												for (int i = 1; i < 13; i++) {
											
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"");
      out.print(i);
      out.write('"');
      out.write('>');
      out.print(i);
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");

												}
											
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- sua lai cai select -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"input-group\" style=\"display: grid;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label for=\"mota\"><b>Loại</b></label> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"Loại SP\" name=\"loai\" required>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"input-group\" style=\"display: grid;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label for=\"mota\"><b>Nhóm</b></label> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"Nhom SP\" name=\"nhom\" required>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"input-group\" style=\"display: grid;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label for=\"mota\"><b>Hình ảnh</b></label> <input type=\"file\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tname=\"photo\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"right\" colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<button type=\"submit\" class=\"btn btn-success\">Gửi</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-danger\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata-dismiss=\"modal\">Đóng</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- dinh dang trang in -->\r\n");
      out.write("\t<div style=\"display: none;\">\r\n");
      out.write("\t\t<div id='printarea'>\r\n");
      out.write("\t\t\t<table>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th title=\"Số thứ tự\" style=\"width: 5%\">STT</th>\r\n");
      out.write("\t\t\t\t\t<th title=\"Mã san pham\" style=\"width: 10%\">Mã</th>\r\n");
      out.write("\t\t\t\t\t<th style=\"width: 20%\">Tên</th>\r\n");
      out.write("\t\t\t\t\t<th style=\"width: 10%\">Giá bán</th>\r\n");
      out.write("\t\t\t\t\t<th style=\"width: 10%\">Hình ảnh</th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t");

					int count2 = 1;
					for (Product c : list) {
				
      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>");
      out.print(count2);
      out.write("</th>\r\n");
      out.write("\t\t\t\t\t<td style=\"text-align: center\">");
      out.print(c.getId());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(c.getName());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t");

						DecimalFormat formatter = new DecimalFormat("###,###,###");
					
      out.write("\r\n");
      out.write("\t\t\t\t\t<td style=\"text-align: center\">");
      out.print(formatter.format(c.getPrice()));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"text-align: center\"><img\r\n");
      out.write("\t\t\t\t\t\tsrc=\"");
      out.print(request.getContextPath());
      out.write('/');
      out.print(c.getLinkHA1());
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"img-responsive img-thumbnail\" style=\"width: 30%\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t");

					count2++;
					}
				
      out.write("\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- in trang web -->\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tfunction printFunc() {\r\n");
      out.write("\t\t\tvar divToPrint = document.getElementById('printarea');\r\n");
      out.write("\t\t\tvar htmlToPrint = '' + '<style type=\"text/css\">'\r\n");
      out.write("\t\t\t\t\t+ 'table th, table td {' + 'border:1px solid #000;'\r\n");
      out.write("\t\t\t\t\t+ 'padding;0.5em;' + '}' + '</style>';\r\n");
      out.write("\t\t\thtmlToPrint += divToPrint.outerHTML;\r\n");
      out.write("\t\t\tnewWin = window.open(\"\");\r\n");
      out.write("\t\t\tnewWin.document.write(\"<h3 align='center'>Quản lí sản phẩm</h3>\");\r\n");
      out.write("\t\t\tnewWin.document.write(htmlToPrint);\r\n");
      out.write("\t\t\tnewWin.print();\r\n");
      out.write("\t\t\tnewWin.close();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<!-- phan trang -->\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t$(document).ready(function() {\r\n");
      out.write("\t\t\t$('#example').dataTable({\r\n");
      out.write("\t\t\t\t\"language\" : {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"sEmptyTable\" : \"Không có dữ liệu để hiển thị\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"sInfo\" : \"Đang hiển thị _START_ đến _END_ của _TOTAL_ sản phẩm\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"sInfoEmpty\" : \"0 bis 0 von 0 Einträgen\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"sInfoFiltered\" : \"(Lọc từ  _MAX_ sản phẩm)\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"sInfoPostFix\" : \"\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"sInfoThousands\" : \".\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"sLengthMenu\" : \"Hiển thị _MENU_ sản phẩm\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"sLoadingRecords\" : \"Wird geladen...\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"sProcessing\" : \"Bitte warten...\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"sSearch\" : \"Tìm kiếm\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"sZeroRecords\" : \"Keine Einträge vorhanden.\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"oPaginate\" : {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"sFirst\" : \"Erste\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"sPrevious\" : \"Trang trước\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"sNext\" : \"Trang sau\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"sLast\" : \"Letzte\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"oAria\" : {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"sSortAscending\" : \": aktivieren, um Spalte aufsteigend zu sortieren\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"sSortDescending\" : \": aktivieren, um Spalte absteigend zu sortieren\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t\"use strict\";\r\n");
      out.write("\t\tfunction submitForm(oFormElement) {\r\n");
      out.write("\t\t\tvar xhr = new XMLHttpRequest();\r\n");
      out.write("\t\t\txhr.onload = function() {\r\n");
      out.write("\t\t\t\tswal({\r\n");
      out.write("\t\t\t\t\tposition : 'top-end',\r\n");
      out.write("\t\t\t\t\ttype : 'success',\r\n");
      out.write("\t\t\t\t\ttitle : xhr.responseText,\r\n");
      out.write("\t\t\t\t\tshowConfirmButton : false,\r\n");
      out.write("\t\t\t\t\ttimer : 1000,\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\twindow.setTimeout(function() {\r\n");
      out.write("\t\t\t\t\tlocation.reload();\r\n");
      out.write("\t\t\t\t}, 1000);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\txhr.open(oFormElement.method, oFormElement.action, true);\r\n");
      out.write("\t\t\txhr.send(new FormData(oFormElement));\r\n");
      out.write("\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- dam bao xoa \r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tdocument.querySelector('#from1').addEventListener('submit',\r\n");
      out.write("\t\t\t\tfunction(e) {\r\n");
      out.write("\t\t\t\t\tvar form = this;\r\n");
      out.write("\t\t\t\t\te.preventDefault();\r\n");
      out.write("\t\t\t\t\tswal({\r\n");
      out.write("\t\t\t\t\t\ttitle : \"Bạn có chắc chắn muốn xóa?\",\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\ttype : \"warning\",\r\n");
      out.write("\t\t\t\t\t\tshowCancelButton : true,\r\n");
      out.write("\t\t\t\t\t\tconfirmButtonColor : \"#DD6B55\",\r\n");
      out.write("\t\t\t\t\t\tconfirmButtonText : \"Yes.\",\r\n");
      out.write("\t\t\t\t\t\tcancelButtonText : \"No.\",\r\n");
      out.write("\t\t\t\t\t\tcloseOnConfirm : false,\r\n");
      out.write("\t\t\t\t\t\tcloseOnCancel : false,\r\n");
      out.write("\t\t\t\t\t\tdangerMode : true,\r\n");
      out.write("\t\t\t\t\t}).then(function(isConfirm) {\r\n");
      out.write("\t\t\t\t\t\tform.submit();\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- xac nhan xoa SP \r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tdocument.querySelector('#from1').addEventListener('click',\r\n");
      out.write("\t\t\t\tfunction(e) {\r\n");
      out.write("\t\t\t\t\tvar form = this;\r\n");
      out.write("\t\t\t\t\te.preventDefault();\r\n");
      out.write("\t\t\t\t\tswal({\r\n");
      out.write("\t\t\t\t\t\ttitle : \"Bạn có chắc chắn muốn xóa?\",\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\ttype : \"warning\",\r\n");
      out.write("\t\t\t\t\t\tshowCancelButton : true,\r\n");
      out.write("\t\t\t\t\t\tconfirmButtonColor : \"#DD6B55\",\r\n");
      out.write("\t\t\t\t\t\tconfirmButtonText : \"Yes.\",\r\n");
      out.write("\t\t\t\t\t\tcancelButtonText : \"No.\",\r\n");
      out.write("\t\t\t\t\t\tcloseOnConfirm : false,\r\n");
      out.write("\t\t\t\t\t\tcloseOnCancel : false,\r\n");
      out.write("\t\t\t\t\t\tdangerMode : true,\r\n");
      out.write("\t\t\t\t\t}).then(function(isConfirm) {\r\n");
      out.write("\t\t\t\t\t\tform.click();\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Thu gon menu -->\r\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/newjs/classie.js\"></script>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tvar menuLeft = document.getElementById('cbp-spmenu-s1'), showLeftPush = document\r\n");
      out.write("\t\t\t\t.getElementById('showLeftPush'), body = document.body;\r\n");
      out.write("\r\n");
      out.write("\t\tshowLeftPush.onclick = function() {\r\n");
      out.write("\t\t\tclassie.toggle(this, 'active');\r\n");
      out.write("\t\t\tclassie.toggle(body, 'cbp-spmenu-push-toright');\r\n");
      out.write("\t\t\tclassie.toggle(menuLeft, 'cbp-spmenu-open');\r\n");
      out.write("\t\t\tdisableOther('showLeftPush');\r\n");
      out.write("\t\t};\r\n");
      out.write("\r\n");
      out.write("\t\tfunction disableOther(button) {\r\n");
      out.write("\t\t\tif (button !== 'showLeftPush') {\r\n");
      out.write("\t\t\t\tclassie.toggle(showLeftPush, 'disabled');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<!-- //thu gon menu -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- side nav js -->\r\n");
      out.write("\t<script src='");
      out.print(request.getContextPath());
      out.write("/newjs/SidebarNav.min.js'\r\n");
      out.write("\t\ttype='text/javascript'></script>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t$('.sidebar-menu').SidebarNav()\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<!-- Bootstrap Core JavaScript -->\r\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/newjs/bootstrap.js\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
