/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.50
 * Generated at: 2020-02-18 13:05:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import model_user.LoginDAO;
import model_shoppingcart.InvoiceDB;
import model_shoppingcart.Invoice;
import java.util.ArrayList;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("model_user.LoginDAO");
    _jspx_imports_classes.add("model_shoppingcart.Invoice");
    _jspx_imports_classes.add("model_shoppingcart.InvoiceDB");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>index</title>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<meta name=\"keywords\"\r\n");
      out.write("\tcontent=\"Glance Design Dashboard Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, \r\n");
      out.write("SmartPhone Compatible web template, free WebDesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design\" />\r\n");
      out.write("<script type=\"application/x-javascript\">\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t addEventListener(\"load\", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap Core CSS -->\r\n");
      out.write("<link href=\"");
      out.print(request.getContextPath());
      out.write("/newcss/bootstrap.css\"\r\n");
      out.write("\trel='stylesheet' type='text/css' />\r\n");
      out.write("\r\n");
      out.write("<!-- Custom CSS -->\r\n");
      out.write("<link href=\"");
      out.print(request.getContextPath());
      out.write("/newcss/style.css\"\r\n");
      out.write("\trel='stylesheet' type='text/css' />\r\n");
      out.write("\r\n");
      out.write("<!-- font-awesome icons CSS -->\r\n");
      out.write("<link href=\"");
      out.print(request.getContextPath());
      out.write("/newcss/font-awesome.css\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<!-- //font-awesome icons CSS-->\r\n");
      out.write("\r\n");
      out.write("<!-- side nav css file -->\r\n");
      out.write("<link href='");
      out.print(request.getContextPath());
      out.write("/newcss/SidebarNav.min.css'\r\n");
      out.write("\tmedia='all' rel='stylesheet' type='text/css' />\r\n");
      out.write("<!-- //side nav css file -->\r\n");
      out.write("\r\n");
      out.write("<!-- js-->\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/newjs/jquery-1.11.1.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/newjs/modernizr.custom.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!--webfonts-->\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"//fonts.googleapis.com/css?family=PT+Sans:400,400i,700,700i&amp;subset=cyrillic,cyrillic-ext,latin-ext\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<!--//webfonts-->\r\n");
      out.write("\r\n");
      out.write("<!-- Metis Menu -->\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/newjs/metisMenu.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/newjs/custom.js\"></script>\r\n");
      out.write("<link href=\"");
      out.print(request.getContextPath());
      out.write("/newjs/custom.css\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<!--//Metis Menu -->\r\n");
      out.write("<style>\r\n");
      out.write("#chartdiv {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 295px;\r\n");
      out.write("}\r\n");
      out.write("/* Style the tab */\r\n");
      out.write(".tab {\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("\tborder: 1px solid #ccc;\r\n");
      out.write("\tbackground-color: #f1f1f1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Style the buttons inside the tab */\r\n");
      out.write(".tab button {\r\n");
      out.write("\tbackground-color: inherit;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tborder: none;\r\n");
      out.write("\toutline: none;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("\tpadding: 14px 16px;\r\n");
      out.write("\ttransition: 0.3s;\r\n");
      out.write("\tfont-size: 17px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Change background color of buttons on hover */\r\n");
      out.write(".tab button:hover {\r\n");
      out.write("\tbackground-color: #ddd;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Create an active/current tablink class */\r\n");
      out.write(".tab button.active {\r\n");
      out.write("\tbackground-color: #ccc;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Style the tab content */\r\n");
      out.write(".tabcontent {\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("\tpadding: 6px 12px;\r\n");
      out.write("\tborder: 1px solid #ccc;\r\n");
      out.write("\tborder-top: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Style the close button */\r\n");
      out.write(".topright {\r\n");
      out.write("\tfloat: right;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("\tfont-size: 28px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".topright:hover {\r\n");
      out.write("\tcolor: red;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<!-- requried-jsfiles-for owl -->\r\n");
      out.write("<link href=\"");
      out.print(request.getContextPath());
      out.write("/cssAdmin/owl.carousel.css\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/jsAdmin/owl.carousel.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\t\t$(\"#owl-demo\").owlCarousel({\r\n");
      out.write("\t\t\titems : 3,\r\n");
      out.write("\t\t\tlazyLoad : true,\r\n");
      out.write("\t\t\tautoPlay : true,\r\n");
      out.write("\t\t\tpagination : true,\r\n");
      out.write("\t\t\tnav : true,\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("<!-- //requried-jsfiles-for owl -->\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"cbp-spmenu-push\">\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/admin/menu.jsp", out, false);
      out.write("\r\n");
      out.write("\t<!-- main content start-->\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<div id=\"page-wrapper\">\r\n");
      out.write("\t\t<div class=\"main-page\">\r\n");
      out.write("\t\t\t<div class=\"col_3\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-3 widget widget1\">\r\n");
      out.write("\t\t\t\t\t<div class=\"r3_counter_box\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"pull-left fa fa-dollar icon-rounded\"></i>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"stats\">\r\n");
      out.write("\t\t\t\t\t\t\t<h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t<strong>$452</strong>\r\n");
      out.write("\t\t\t\t\t\t\t</h5>\r\n");
      out.write("\t\t\t\t\t\t\t<span>Total Revenue</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-3 widget widget1\">\r\n");
      out.write("\t\t\t\t\t<div class=\"r3_counter_box\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"pull-left fa fa-laptop user1 icon-rounded\"></i>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"stats\">\r\n");
      out.write("\t\t\t\t\t\t\t<h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t<strong>$1019</strong>\r\n");
      out.write("\t\t\t\t\t\t\t</h5>\r\n");
      out.write("\t\t\t\t\t\t\t<span>Online Revenue</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-3 widget widget1\">\r\n");
      out.write("\t\t\t\t\t<div class=\"r3_counter_box\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"pull-left fa fa-money user2 icon-rounded\"></i>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"stats\">\r\n");
      out.write("\t\t\t\t\t\t\t<h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t<strong>$1012</strong>\r\n");
      out.write("\t\t\t\t\t\t\t</h5>\r\n");
      out.write("\t\t\t\t\t\t\t<span>Expenses</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-3 widget widget1\">\r\n");
      out.write("\t\t\t\t\t<div class=\"r3_counter_box\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"pull-left fa fa-pie-chart dollar1 icon-rounded\"></i>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"stats\">\r\n");
      out.write("\t\t\t\t\t\t\t<h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t<strong>$450</strong>\r\n");
      out.write("\t\t\t\t\t\t\t</h5>\r\n");
      out.write("\t\t\t\t\t\t\t<span>Expenditure</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-3 widget\">\r\n");
      out.write("\t\t\t\t\t<div class=\"r3_counter_box\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"pull-left fa fa-users dollar2 icon-rounded\"></i>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"stats\">\r\n");
      out.write("\t\t\t\t\t\t\t<h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t<strong>");
      out.print(new LoginDAO().countUser() );
      out.write("</strong>\r\n");
      out.write("\t\t\t\t\t\t\t</h5>\r\n");
      out.write("\t\t\t\t\t\t\t<span>Total Users</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div style=\"margin-left: 5%; width: 95%;\">\r\n");
      out.write("\t\t\t\t<div class=\"row-one widgettable\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-11 content-top-2 card\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"agileinfo-cdr\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"tab\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<button class=\"tablinks\" onclick=\"openCity(event, 'London')\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tid=\"defaultOpen\">Gửi mail cho tất cả khách hàng</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t<button class=\"tablinks\" onclick=\"openCity(event, 'Paris')\">Gửi\r\n");
      out.write("\t\t\t\t\t\t\t\t\tmail cho cá nhân</button>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"London\" class=\"tabcontent\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span onclick=\"this.parentElement.style.display='none'\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"topright\">&times</span>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<form>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr style=\"background: none;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td style=\"border: none; font-size: 17px\">Tiêu đề <label\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"color: red\">*</label></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td style=\"border: none\"><input style=\"width: 100%\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\trequired=\"required\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td>&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr style=\"background: none;; margin-top: 10px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td style=\"border: none; font-size: 17px; margin-top: 10px\">Nội\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdung <label style=\"color: red\">*</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td style=\"border: none; margin-top: 10px\"><textarea\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\trows=\"5\" cols=\"50\" style=\"width: 100%;\"></textarea></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr style=\"background: none;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td style=\"border: none; font-size: 17px\">Tệp đính kèm</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td style=\"border: none; font-size: 17px\"><input\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"width: 100%\" type=\"file\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr style=\"background: none;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"border: none; font-size: 17px; text-align: right; margin-right: 0px;\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tcolspan=\"2\"><input type=\"submit\" value=\"Cập nhật\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"background: #34B67A; color: white; border: none; padding: 8px 40px\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"Paris\" class=\"tabcontent\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span onclick=\"this.parentElement.style.display='none'\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"topright\">&times</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<form>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr style=\"background: none;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td style=\"border: none; font-size: 17px\">Người nhận<label\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"color: red\">*</label></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td style=\"border: none\"><input style=\"width: 100%\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\trequired=\"required\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td>&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr style=\"background: none;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td style=\"border: none; font-size: 17px\">Tiêu đề <label\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"color: red\">*</label></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td style=\"border: none\"><input style=\"width: 100%\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\trequired=\"required\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td>&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr style=\"background: none;; margin-top: 10px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td style=\"border: none; font-size: 17px; margin-top: 10px\">Nội\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdung <label style=\"color: red\">*</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td style=\"border: none; margin-top: 10px\"><textarea\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\trows=\"5\" cols=\"50\" style=\"width: 100%;\"></textarea></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr style=\"background: none;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td style=\"border: none; font-size: 17px\">Tệp đính kèm</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td style=\"border: none; font-size: 17px\"><input\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"width: 100%\" type=\"file\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr style=\"background: none;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"border: none; font-size: 17px; text-align: right; margin-right: 0px;\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tcolspan=\"2\"><input type=\"submit\" value=\"Cập nhật\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"background: #34B67A; color: white; border: none; padding: 8px 40px\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- footeer -->\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tfunction openCity(evt, cityName) {\r\n");
      out.write("\t\t\tvar i, tabcontent, tablinks;\r\n");
      out.write("\t\t\ttabcontent = document.getElementsByClassName(\"tabcontent\");\r\n");
      out.write("\t\t\tfor (i = 0; i < tabcontent.length; i++) {\r\n");
      out.write("\t\t\t\ttabcontent[i].style.display = \"none\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\ttablinks = document.getElementsByClassName(\"tablinks\");\r\n");
      out.write("\t\t\tfor (i = 0; i < tablinks.length; i++) {\r\n");
      out.write("\t\t\t\ttablinks[i].className = tablinks[i].className.replace(\r\n");
      out.write("\t\t\t\t\t\t\" active\", \"\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tdocument.getElementById(cityName).style.display = \"block\";\r\n");
      out.write("\t\t\tevt.currentTarget.className += \" active\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t// Get the element with id=\"defaultOpen\" and click on it\r\n");
      out.write("\t\tdocument.getElementById(\"defaultOpen\").click();\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Classie -->\r\n");
      out.write("\t<!-- Thu gon menu -->\r\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/newjs/classie.js\"></script>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tvar menuLeft = document.getElementById('cbp-spmenu-s1'), showLeftPush = document\r\n");
      out.write("\t\t\t\t.getElementById('showLeftPush'), body = document.body;\r\n");
      out.write("\r\n");
      out.write("\t\tshowLeftPush.onclick = function() {\r\n");
      out.write("\t\t\tclassie.toggle(this, 'active');\r\n");
      out.write("\t\t\tclassie.toggle(body, 'cbp-spmenu-push-toright');\r\n");
      out.write("\t\t\tclassie.toggle(menuLeft, 'cbp-spmenu-open');\r\n");
      out.write("\t\t\tdisableOther('showLeftPush');\r\n");
      out.write("\t\t};\r\n");
      out.write("\r\n");
      out.write("\t\tfunction disableOther(button) {\r\n");
      out.write("\t\t\tif (button !== 'showLeftPush') {\r\n");
      out.write("\t\t\t\tclassie.toggle(showLeftPush, 'disabled');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<!-- //Classie -->\r\n");
      out.write("\t<!-- //thu gon menu -->\r\n");
      out.write("\t<!-- side nav js -->\r\n");
      out.write("\t<script src='");
      out.print(request.getContextPath());
      out.write("/newjs/SidebarNav.min.js'\r\n");
      out.write("\t\ttype='text/javascript'></script>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t$('.sidebar-menu').SidebarNav()\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<!-- //side nav js -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- Bootstrap Core JavaScript -->\r\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/newjs/bootstrap.js\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<!-- //Bootstrap Core JavaScript -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
