/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.50
 * Generated at: 2020-02-18 13:23:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin.report;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class reports_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>report</title>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<meta name=\"keywords\"\r\n");
      out.write("\tcontent=\"Glance Design Dashboard Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, \r\n");
      out.write("SmartPhone Compatible web template, free WebDesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design\" />\r\n");
      out.write("<script type=\"application/x-javascript\">\r\n");
      out.write("\t\r\n");
      out.write("\t addEventListener(\"load\", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap Core CSS -->\r\n");
      out.write("<link href=\"");
      out.print(request.getContextPath());
      out.write("/newcss/bootstrap.css\"\r\n");
      out.write("\trel='stylesheet' type='text/css' />\r\n");
      out.write("\r\n");
      out.write("<!-- Custom CSS -->\r\n");
      out.write("<link href=\"");
      out.print(request.getContextPath());
      out.write("/newcss/style.css\"\r\n");
      out.write("\trel='stylesheet' type='text/css' />\r\n");
      out.write("\r\n");
      out.write("<!-- font-awesome icons CSS -->\r\n");
      out.write("<link href=\"");
      out.print(request.getContextPath());
      out.write("/newcss/font-awesome.css\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<!-- //font-awesome icons CSS-->\r\n");
      out.write("\r\n");
      out.write("<!-- side nav css file -->\r\n");
      out.write("<link href='");
      out.print(request.getContextPath());
      out.write("/newcss/SidebarNav.min.css'\r\n");
      out.write("\tmedia='all' rel='stylesheet' type='text/css' />\r\n");
      out.write("<!-- //side nav css file -->\r\n");
      out.write("\r\n");
      out.write("<!-- js-->\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/newjs/jquery-1.11.1.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/newjs/modernizr.custom.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!--webfonts-->\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"//fonts.googleapis.com/css?family=PT+Sans:400,400i,700,700i&amp;subset=cyrillic,cyrillic-ext,latin-ext\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<!--//webfonts-->\r\n");
      out.write("\r\n");
      out.write("<!-- Metis Menu -->\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/newjs/metisMenu.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/newjs/custom.js\"></script>\r\n");
      out.write("<link href=\"");
      out.print(request.getContextPath());
      out.write("/newjs/custom.css\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<!--//Metis Menu -->\r\n");
      out.write("<style>\r\n");
      out.write("#chartdiv {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 295px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<!-- requried-jsfiles-for owl -->\r\n");
      out.write("<link href=\"");
      out.print(request.getContextPath());
      out.write("/cssAdmin/owl.carousel.css\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/jsAdmin/owl.carousel.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\t\t$(\"#owl-demo\").owlCarousel({\r\n");
      out.write("\t\t\titems : 3,\r\n");
      out.write("\t\t\tlazyLoad : true,\r\n");
      out.write("\t\t\tautoPlay : true,\r\n");
      out.write("\t\t\tpagination : true,\r\n");
      out.write("\t\t\tnav : true,\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("<!-- //requried-jsfiles-for owl -->\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"cbp-spmenu-push\">\r\n");
      out.write("\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/admin/menu.jsp", out, false);
      out.write("\r\n");
      out.write("\t<!-- main content start-->\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<br>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"page-wrapper\">\r\n");
      out.write("\t\t<div class=\"main-page\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"wrap\" style=\"width: 90%; float: right; margin-right: 3%;\">\r\n");
      out.write("\t\t\t\t<div class=\"bg-effect\">\r\n");
      out.write("\t\t\t\t\t<h2>Chọn loại báo cáo</h2>\r\n");
      out.write("\t\t\t\t\t<ul class=\"bt-list\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/ControllerAdmin?action=displayReport&name=userReport&title=KhachHang\" class=\"hvr-icon-grow-rotate col-1\">Khách\r\n");
      out.write("\t\t\t\t\t\t\t\thàng mua hàng</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" class=\"hvr-icon-forward col-2\">Sản phẩm bán ra</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" class=\"hvr-icon-down col-3\">Chi tiết hóa\r\n");
      out.write("\t\t\t\t\t\t\t\tđơn từng khách hàng</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"");
      out.print(request.getContextPath());
      out.write("/admin/report/parameter.jsp?Name=DanhSachHoaDon&title=Danh sách hóa đơn\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"hvr-icon-up col-4\">Toàn bộ hóa đơn(Tổng quát)</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" class=\"hvr-icon-spin col-5\">Biểu đồ thống\r\n");
      out.write("\t\t\t\t\t\t\t\tkê</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" class=\"hvr-icon-drop col-6\">Số lượt truy cập web</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--footer-->\r\n");
      out.write("\t<div class=\"footer\">\r\n");
      out.write("\t\t<p>\r\n");
      out.write("\t\t\t&copy; 2018 Glance Design Dashboard. All Rights Reserved | Design by\r\n");
      out.write("\t\t\t<a href=\"#\" target=\"_blank\">w3layouts</a>\r\n");
      out.write("\t\t</p>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--//footer-->\r\n");
      out.write("\t<!-- Classie -->\r\n");
      out.write("\t<!-- Thu gon menu -->\r\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/newjs/classie.js\"></script>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tvar menuLeft = document.getElementById('cbp-spmenu-s1'), showLeftPush = document\r\n");
      out.write("\t\t\t\t.getElementById('showLeftPush'), body = document.body;\r\n");
      out.write("\r\n");
      out.write("\t\tshowLeftPush.onclick = function() {\r\n");
      out.write("\t\t\tclassie.toggle(this, 'active');\r\n");
      out.write("\t\t\tclassie.toggle(body, 'cbp-spmenu-push-toright');\r\n");
      out.write("\t\t\tclassie.toggle(menuLeft, 'cbp-spmenu-open');\r\n");
      out.write("\t\t\tdisableOther('showLeftPush');\r\n");
      out.write("\t\t};\r\n");
      out.write("\r\n");
      out.write("\t\tfunction disableOther(button) {\r\n");
      out.write("\t\t\tif (button !== 'showLeftPush') {\r\n");
      out.write("\t\t\t\tclassie.toggle(showLeftPush, 'disabled');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<!-- //Classie -->\r\n");
      out.write("\t<!-- //thu gon menu -->\r\n");
      out.write("\t<!-- side nav js -->\r\n");
      out.write("\t<script src='");
      out.print(request.getContextPath());
      out.write("/newjs/SidebarNav.min.js'\r\n");
      out.write("\t\ttype='text/javascript'></script>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t$('.sidebar-menu').SidebarNav()\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<!-- //side nav js -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- Bootstrap Core JavaScript -->\r\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/newjs/bootstrap.js\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<!-- //Bootstrap Core JavaScript -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
