/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.50
 * Generated at: 2020-03-16 04:10:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin.unprocess_005finvoice;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import model_shoppingcart.ItemCart;
import java.text.DecimalFormat;
import model_shoppingcart.Invoice;
import java.util.ArrayList;

public final class invoices_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("model_shoppingcart.Invoice");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("model_shoppingcart.ItemCart");
    _jspx_imports_classes.add("java.text.DecimalFormat");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Invoices</title>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<meta name=\"keywords\"\r\n");
      out.write("\tcontent=\"Glance Design Dashboard Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, \r\n");
      out.write("SmartPhone Compatible web template, free WebDesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design\" />\r\n");
      out.write("<script type=\"application/x-javascript\">\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t addEventListener(\"load\", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap Core CSS -->\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/newcss/bootstrap.css\"\r\n");
      out.write("\trel='stylesheet' type='text/css' />\r\n");
      out.write("\r\n");
      out.write("<!-- Custom CSS -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/newcss/style.css\" />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- font-awesome icons CSS -->\r\n");
      out.write("<link href=\"");
      out.print(request.getContextPath());
      out.write("/newcss/font-awesome.css\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<!-- //font-awesome icons CSS-->\r\n");
      out.write("\r\n");
      out.write("<!-- side nav css file -->\r\n");
      out.write("<link href=\"");
      out.print(request.getContextPath());
      out.write("/newcss/SidebarNav.min.css\"\r\n");
      out.write("\tmedia='all' rel='stylesheet' type='text/css' />\r\n");
      out.write("<!-- //side nav css file -->\r\n");
      out.write("\r\n");
      out.write("<!-- js-->\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/newjs/jquery-1.11.1.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/newjs/modernizr.custom.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!--webfonts-->\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"//fonts.googleapis.com/css?family=PT+Sans:400,400i,700,700i&amp;subset=cyrillic,cyrillic-ext,latin-ext\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<!--//webfonts-->\r\n");
      out.write("\r\n");
      out.write("<!-- Metis Menu -->\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/newjs/metisMenu.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/newjs/custom.js\"></script>\r\n");
      out.write("<link href=\"");
      out.print(request.getContextPath());
      out.write("/newjs/custom.css\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<!--//Metis Menu -->\r\n");
      out.write("<!-- phan trang -->\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.3.1.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap.min.js\"></script>\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap.min.css\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<style>\r\n");
      out.write("#chartdiv {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 295px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<!-- requried-jsfiles-for owl -->\r\n");
      out.write("<link href=\"");
      out.print(request.getContextPath());
      out.write("/cssAdmin/owl.carousel.css\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/jsAdmin/owl.carousel.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\t\t$(\"#owl-demo\").owlCarousel({\r\n");
      out.write("\t\t\titems : 3,\r\n");
      out.write("\t\t\tlazyLoad : true,\r\n");
      out.write("\t\t\tautoPlay : true,\r\n");
      out.write("\t\t\tpagination : true,\r\n");
      out.write("\t\t\tnav : true,\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("<!-- //requried-jsfiles-for owl -->\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("* {\r\n");
      out.write("\tfont-size: 16px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"cbp-spmenu-push\">\r\n");
      out.write("\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/admin/menu.jsp", out, false);
      out.write("\r\n");
      out.write("\t<!-- main content start-->\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<div id=\"page-wrapper\">\r\n");
      out.write("\t\t<div class=\"main-page\">\r\n");
      out.write("\t\t\t<div class=\"col_3\">\r\n");
      out.write("\t\t\t\t<h3 style=\"text-align: center\">DANH SÁCH HÓA ĐƠN CHƯA XỬ LÍ</h3>\r\n");
      out.write("\t\t\t\t<div class=\"button_set_one\"\r\n");
      out.write("\t\t\t\t\tstyle=\"width: 85%; float: right; margin-right: 8%;\">\r\n");
      out.write("\t\t\t\t\t<div style=\"float: right; margin-right: 2%;\">\r\n");
      out.write("\t\t\t\t\t\t<a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"");
      out.print(request.getContextPath());
      out.write("/ControllerAdmin?action=displayReport&name=unprocessInvoice\"><button\r\n");
      out.write("\t\t\t\t\t\t\t\ttype=\"button\" class=\"btn btn-default\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"fa fa-file-text-o\"></span>&nbsp;Xuất excel\r\n");
      out.write("\t\t\t\t\t\t\t</button></a>\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-default\" id='btn'\r\n");
      out.write("\t\t\t\t\t\t\tonclick='printFunc();'>\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"fa fa-print\"></span>&nbsp;In\r\n");
      out.write("\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t<a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"");
      out.print(request.getContextPath());
      out.write("/ControllerAdmin?action=allInvoice\"><button\r\n");
      out.write("\t\t\t\t\t\t\t\ttype=\"button\" class=\"btn btn-success\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"\tfa fa-files-o\"></span>&nbsp;Xử lí tất cả\r\n");
      out.write("\t\t\t\t\t\t\t</button></a> <a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"");
      out.print(request.getContextPath());
      out.write("/ControllerAdmin?action=removeAllInvoice\"><button\r\n");
      out.write("\t\t\t\t\t\t\t\ttype=\"button\" class=\"btn btn-danger\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"fa fa-remove-square-o\"></span>&nbsp;Hủy tất cả\r\n");
      out.write("\t\t\t\t\t\t\t</button></a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- the hien noi dung o day -->\r\n");
      out.write("\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\tstyle=\"width: 95%; margin-right: 2%; float: right; margin-top: -3%;\">\r\n");
      out.write("\t\t\t\t\t<div class=\"bs-example widget-shadow\"\r\n");
      out.write("\t\t\t\t\t\tdata-example-id=\"hoverable-table\">\r\n");
      out.write("\t\t\t\t\t\t<table id=\"example\" class=\"table table-hover\">\r\n");
      out.write("\t\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th title=\"Số thứ tự\">STT</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>Tên khách hàng</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>Ngày lập HD</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>Tổng giá</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th></th>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t");

									ArrayList<Invoice> listInvoid = (ArrayList<Invoice>) session.getAttribute("unprocessInvoices");
									int count = 1;
									for (Invoice i : listInvoid) {
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th scope=\"row\">");
      out.print(count);
      out.write("</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>");
      out.print(i.getUser().getFullName());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

										java.text.DateFormat df = new java.text.SimpleDateFormat("dd/MM/yyyy");
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>");
      out.print(df.format(i.getToday().getTime()));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>");
      out.print(i.getShop().totalPrice());
      out.write("</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><a\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\thref=\"");
      out.print(request.getContextPath());
      out.write("/ControllerAdmin?action=displayInvoice&idInvoice=");
      out.print(i.getNumberInvoice());
      out.write("\">Chọn\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tđể xem</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t");

									count++;
									}
								
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- dinh dang trang in -->\r\n");
      out.write("\t<div style=\"display: none;\">\r\n");
      out.write("\t\t<div id='printarea'>\r\n");
      out.write("\t\t\t<table>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th title=\"Số thứ tự\" style=\"width: 5%\">STT</th>\r\n");
      out.write("\t\t\t\t\t<th style=\"width: 10%\">Mã</th>\r\n");
      out.write("\t\t\t\t\t<th style=\"width: 20%\">Tên khách hàng</th>\r\n");
      out.write("\t\t\t\t\t<th style=\"width: 20%\">Điện thoại</th>\r\n");
      out.write("\t\t\t\t\t<th style=\"width: 10%\">Ngày giao dịch</th>\r\n");
      out.write("\t\t\t\t\t<th style=\"width: 10%\">Tổng tiền</th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t");

					count = 1;
					for (Invoice i : listInvoid) {
				
      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>");
      out.print(count);
      out.write("</th>\r\n");
      out.write("\t\t\t\t\t<td style=\"text-align: center\">");
      out.print(i.getNumberInvoice());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(i.getUser().getFullName());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(i.getUser().getPhone());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(i.getToday());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t");

						DecimalFormat formatter = new DecimalFormat("###,###,###");
					
      out.write("\r\n");
      out.write("\t\t\t\t\t<td style=\"text-align: center\">");
      out.print(formatter.format(i.getShop().totalPrice()));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"6\" style=\"text-align: left;\">Danh sách sản phẩm:</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<th colspan=\"3\" style=\"text-align: right\">STT</th>\r\n");
      out.write("\t\t\t\t\t<th>Tên SP</th>\r\n");
      out.write("\t\t\t\t\t<th>Giá</th>\r\n");
      out.write("\t\t\t\t\t<th>Số lượng</th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t");

					List<ItemCart> listCart = i.getShop().getListItemcart();
						for (int y = 0; y < listCart.size(); y++) {
							ItemCart item = listCart.get(y);
				
      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\t<td colspan=\"3\" style=\"text-align: right\">");
      out.print(y + 1);
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(item.getP().getName());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(item.getP().getPrice());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(item.getQuantity());
      out.write("</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\t\t\t\t");

					count++;
					}
				
      out.write("\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- in trang web -->\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tfunction printFunc() {\r\n");
      out.write("\t\t\tvar divToPrint = document.getElementById('printarea');\r\n");
      out.write("\t\t\tvar htmlToPrint = '' + '<style type=\"text/css\">'\r\n");
      out.write("\t\t\t\t\t+ 'table th, table td {' + 'border:1px solid #000;'\r\n");
      out.write("\t\t\t\t\t+ 'padding;0.5em;' + '}' + '</style>';\r\n");
      out.write("\t\t\thtmlToPrint += divToPrint.outerHTML;\r\n");
      out.write("\t\t\tnewWin = window.open(\"\");\r\n");
      out.write("\t\t\tnewWin.document.write(\"<h3 align='center'>Quản lí sản phẩm</h3>\");\r\n");
      out.write("\t\t\tnewWin.document.write(htmlToPrint);\r\n");
      out.write("\t\t\tnewWin.print();\r\n");
      out.write("\t\t\tnewWin.close();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<!-- phan trang -->\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\t\t$('#example').dataTable({\r\n");
      out.write("\t\t\t\"language\": {\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\"sEmptyTable\":   \t\"Không có dữ liệu để hiển thị\",\r\n");
      out.write("\t\t\t\t\t\"sInfo\":         \t\"Đang hiển thị _START_ đến _END_ của _TOTAL_ sản phẩm\",\r\n");
      out.write("\t\t\t\t\t\"sInfoEmpty\":    \t\"0 bis 0 von 0 Einträgen\",\r\n");
      out.write("\t\t\t\t\t\"sInfoFiltered\": \t\"(Lọc từ  _MAX_ sản phẩm)\",\r\n");
      out.write("\t\t\t\t\t\"sInfoPostFix\":  \t\"\",\r\n");
      out.write("\t\t\t\t\t\"sInfoThousands\":  \t\".\",\r\n");
      out.write("\t\t\t\t\t\"sLengthMenu\":   \t\"Hiển thị _MENU_ sản phẩm\",\r\n");
      out.write("\t\t\t\t\t\"sLoadingRecords\": \t\"Wird geladen...\",\r\n");
      out.write("\t\t\t\t\t\"sProcessing\":   \t\"Bitte warten...\",\r\n");
      out.write("\t\t\t\t\t\"sSearch\":       \t\"Tìm kiếm\",\r\n");
      out.write("\t\t\t\t\t\"sZeroRecords\":  \t\"Keine Einträge vorhanden.\",\r\n");
      out.write("\t\t\t\t\t\"oPaginate\": {\r\n");
      out.write("\t\t\t\t\t\t\"sFirst\":    \t\"Erste\",\r\n");
      out.write("\t\t\t\t\t\t\"sPrevious\": \t\"Trang trước\",\r\n");
      out.write("\t\t\t\t\t\t\"sNext\":     \t\"Trang sau\",\r\n");
      out.write("\t\t\t\t\t\t\"sLast\":     \t\"Letzte\"\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\"oAria\": {\r\n");
      out.write("\t\t\t\t\t\t\"sSortAscending\":  \": aktivieren, um Spalte aufsteigend zu sortieren\",\r\n");
      out.write("\t\t\t\t\t\t\"sSortDescending\": \": aktivieren, um Spalte absteigend zu sortieren\"\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t        }\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\t \r\n");
      out.write("\t</script>\r\n");
      out.write("\t<!-- Thu gon menu -->\r\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/newjs/classie.js\"></script>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tvar menuLeft = document.getElementById('cbp-spmenu-s1'), showLeftPush = document\r\n");
      out.write("\t\t\t\t.getElementById('showLeftPush'), body = document.body;\r\n");
      out.write("\r\n");
      out.write("\t\tshowLeftPush.onclick = function() {\r\n");
      out.write("\t\t\tclassie.toggle(this, 'active');\r\n");
      out.write("\t\t\tclassie.toggle(body, 'cbp-spmenu-push-toright');\r\n");
      out.write("\t\t\tclassie.toggle(menuLeft, 'cbp-spmenu-open');\r\n");
      out.write("\t\t\tdisableOther('showLeftPush');\r\n");
      out.write("\t\t};\r\n");
      out.write("\r\n");
      out.write("\t\tfunction disableOther(button) {\r\n");
      out.write("\t\t\tif (button !== 'showLeftPush') {\r\n");
      out.write("\t\t\t\tclassie.toggle(showLeftPush, 'disabled');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<!-- //thu gon menu -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- side nav js -->\r\n");
      out.write("\t<script src='");
      out.print(request.getContextPath());
      out.write("/newjs/SidebarNav.min.js'\r\n");
      out.write("\t\ttype='text/javascript'></script>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t$('.sidebar-menu').SidebarNav()\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<!-- //side nav js -->\r\n");
      out.write("\t<!-- Bootstrap Core JavaScript -->\r\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/newjs/bootstrap.js\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<!-- //Bootstrap Core JavaScript -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
